Day3
Sansi2619/new-project pull request #4
Opened 2024-12-23 19:00 UTC by Sansi2619

Pull request

2024-12-28 23:45 UTC, uharishdhoni1991 requested changes

2024-12-28 23:45 UTC, uharishdhoni1991 commented on .github/workflows/main.yml
Can only see a single line text here ! What’s the intention of this file !?

2024-12-29 04:56 UTC, Sansi2619 commented on .github/workflows/main.yml
Just learnt how to pull and merge a file

2025-01-03 17:00 UTC, uharishdhoni1991 approved these changes

2025-01-07 05:39 UTC, Sansi2619 reviewed
Approved

2025-01-08 06:38 UTC, merged